### PR TITLE
Documentation for rotation

### PR DESCRIPTION
**Pull request by pramodin**

### CODE REVIEW

**Comment by otterc** [comment]
@PramodSSImmaneni 
This doesn't tell how the loading of stream  or processing of a tuple changes with rotation

**Comment by pramodin** [comment]
Do any of those affect the user or to a person who is interested in working on the operator itself?

**Comment by otterc** [comment]
1. Please go through the existing document. These sections say about how it changes with rotation and will be explained there.
2. The document explains the operator in details. Isn't the javadoc about the operator enough to understand what each kind of rotation is if we don't want include details of implementation.

**Comment by pramodin** [comment]
I didn't understand the statement.. "These sections say about how it changes with rotation and will be explained there."

I think there are two types of documents. One that explains how the user can use the operator explaining key concepts along the way. It is not a simple reference like Javadoc, it helps the user know the different features, how to use them and at a high level what the feature does.

Another that is intended for the developer who was wants to make changes to the operator. Here you go into detail how the feature is implemented.

The user will not have the time and patience to go through the second document when he wants to figure out how to use the operator.

**Comment by otterc** [comment]
1. The section about the process of loading a stream and processing of a tuple in the existing document.
2.  This document is intended for the developer who wants to extend this operator because it explains the features in the document in detail.

**Pull request merged**
